# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-vm/azure init && terraform -chdir=.isoloom/cloud-vm/azure apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/azure destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

variable "subscription_id" {
  type        = string
  default     = null
  description = "Default: ARM_SUBSCRIPTION_ID from the environment"
}
variable "region" {
  type    = string
  default = "swedencentral"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-sccm-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
  tags = { "isoloom-environment" = "sccm", "managed-by" = "isoloom" }
}

resource "azurerm_resource_group" "env" {
  name     = local.name
  location = var.region
  tags     = local.tags
}

# The environment's networks: one virtual network, a subnet per network with its exact range.
resource "azurerm_virtual_network" "env" {
  name                = local.name
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  address_space       = ["192.168.56.0/24"]
  tags                = local.tags
}

resource "azurerm_subnet" "lab" {
  name                 = "lab"
  resource_group_name  = azurerm_resource_group.env.name
  virtual_network_name = azurerm_virtual_network.env.name
  address_prefixes     = ["192.168.56.0/24"]
}

# The Windows machines' administrator password (user isoloom), for WinRM.
resource "random_password" "windows" {
  length      = 24
  special     = false
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
}

# The controller's own key: it runs the playbooks over SSH on every machine.
resource "tls_private_key" "controller" {
  algorithm = "ED25519"
}

# Machine `dc01` (Windows): what may reach it.
resource "azurerm_network_security_group" "dc01" {
  name                = "${local.name}-dc01"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  security_rule {
    name                       = "net-lab"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "192.168.56.0/24"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "winrm"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "5985"
    source_address_prefix      = var.allowed_cidr
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "outbound"
    priority                   = 100
    direction                  = "Outbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_public_ip" "dc01" {
  name                = "${local.name}-dc01"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}

resource "azurerm_network_interface" "dc01_lab" {
  name                = "${local.name}-dc01-lab"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.lab.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "192.168.56.10"
    public_ip_address_id          = azurerm_public_ip.dc01.id
  }
}

resource "azurerm_network_interface_security_group_association" "dc01_lab" {
  network_interface_id      = azurerm_network_interface.dc01_lab.id
  network_security_group_id = azurerm_network_security_group.dc01.id
}

resource "azurerm_windows_virtual_machine" "dc01" {
  name                  = "${local.name}-dc01"
  computer_name         = "dc01"
  resource_group_name   = azurerm_resource_group.env.name
  location              = var.region
  size                  = "Standard_B2s"
  admin_username        = "isoloom"
  admin_password        = random_password.windows.result
  network_interface_ids = [azurerm_network_interface.dc01_lab.id]
  winrm_listener {
    protocol = "Http"
  }
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
    disk_size_gb         = 127
  }
  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-datacenter-gensecond"
    version   = "latest"
  }
  tags = local.tags
}

resource "terraform_data" "dc01" {
  triggers_replace = [azurerm_windows_virtual_machine.dc01.id]
  connection {
    type     = "winrm"
    host     = azurerm_public_ip.dc01.ip_address
    user     = "isoloom"
    password = random_password.windows.result
    https    = false
    use_ntlm = true
    timeout  = "30m"
  }
  provisioner "remote-exec" {
    inline = [var.auto_stop_minutes > 0 ? "powershell -NoProfile -Command \"Register-ScheduledTask -TaskName isoloom-auto-stop -Action (New-ScheduledTaskAction -Execute shutdown.exe -Argument '/s /t 0') -Trigger (New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(${var.auto_stop_minutes})) -User SYSTEM -RunLevel Highest -Force\"" : "cmd /c ver"]
  }
  provisioner "file" {
    source      = "${local.root}/vagrant/ConfigureRemotingForAnsible.ps1"
    destination = "C:/isoloom/vagrant/ConfigureRemotingForAnsible.ps1"
  }
  provisioner "file" {
    content     = "$ErrorActionPreference = 'Stop'\nif ($env:COMPUTERNAME -ne 'DC01') { throw \"still named $env:COMPUTERNAME: the rename hasn't taken effect\" }\nAdd-Content -Path \"$env:windir\\System32\\drivers\\etc\\hosts\" -Value @('192.168.56.11 srv01', '192.168.56.12 srv02', '192.168.56.13 ws01')\nNew-NetFirewallRule -DisplayName 'isoloom 53' -Direction Inbound -Protocol TCP -LocalPort 53 -Action Allow | Out-Null\nNew-NetFirewallRule -DisplayName 'isoloom 88' -Direction Inbound -Protocol TCP -LocalPort 88 -Action Allow | Out-Null\nNew-NetFirewallRule -DisplayName 'isoloom 389' -Direction Inbound -Protocol TCP -LocalPort 389 -Action Allow | Out-Null\nNew-NetFirewallRule -DisplayName 'isoloom 445' -Direction Inbound -Protocol TCP -LocalPort 445 -Action Allow | Out-Null\nNew-Item -ItemType Directory -Force C:\\ProgramData\\isoloom | Out-Null; Set-Content C:\\ProgramData\\isoloom\\ready 'ready'\n& powershell -NoProfile -ExecutionPolicy Bypass -File 'C:\\isoloom\\vagrant\\ConfigureRemotingForAnsible.ps1'; if ($LASTEXITCODE) { exit $LASTEXITCODE }\n"
    destination = "C:/isoloom/setup.ps1"
  }
  provisioner "remote-exec" {
    inline = ["powershell -NoProfile -ExecutionPolicy Bypass -File C:/isoloom/setup.ps1"]
  }
}

# Machine `srv01` (Windows): what may reach it.
resource "azurerm_network_security_group" "srv01" {
  name                = "${local.name}-srv01"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  security_rule {
    name                       = "net-lab"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "192.168.56.0/24"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "winrm"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "5985"
    source_address_prefix      = var.allowed_cidr
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "outbound"
    priority                   = 100
    direction                  = "Outbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_public_ip" "srv01" {
  name                = "${local.name}-srv01"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}

resource "azurerm_network_interface" "srv01_lab" {
  name                = "${local.name}-srv01-lab"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.lab.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "192.168.56.11"
    public_ip_address_id          = azurerm_public_ip.srv01.id
  }
}

resource "azurerm_network_interface_security_group_association" "srv01_lab" {
  network_interface_id      = azurerm_network_interface.srv01_lab.id
  network_security_group_id = azurerm_network_security_group.srv01.id
}

resource "azurerm_windows_virtual_machine" "srv01" {
  name                  = "${local.name}-srv01"
  computer_name         = "srv01"
  resource_group_name   = azurerm_resource_group.env.name
  location              = var.region
  size                  = "Standard_B2s"
  admin_username        = "isoloom"
  admin_password        = random_password.windows.result
  network_interface_ids = [azurerm_network_interface.srv01_lab.id]
  winrm_listener {
    protocol = "Http"
  }
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
    disk_size_gb         = 127
  }
  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-datacenter-gensecond"
    version   = "latest"
  }
  tags = local.tags
}

resource "terraform_data" "srv01" {
  triggers_replace = [azurerm_windows_virtual_machine.srv01.id]
  connection {
    type     = "winrm"
    host     = azurerm_public_ip.srv01.ip_address
    user     = "isoloom"
    password = random_password.windows.result
    https    = false
    use_ntlm = true
    timeout  = "30m"
  }
  provisioner "remote-exec" {
    inline = [var.auto_stop_minutes > 0 ? "powershell -NoProfile -Command \"Register-ScheduledTask -TaskName isoloom-auto-stop -Action (New-ScheduledTaskAction -Execute shutdown.exe -Argument '/s /t 0') -Trigger (New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(${var.auto_stop_minutes})) -User SYSTEM -RunLevel Highest -Force\"" : "cmd /c ver"]
  }
  provisioner "file" {
    source      = "${local.root}/vagrant/ConfigureRemotingForAnsible.ps1"
    destination = "C:/isoloom/vagrant/ConfigureRemotingForAnsible.ps1"
  }
  provisioner "file" {
    content     = "$ErrorActionPreference = 'Stop'\nif ($env:COMPUTERNAME -ne 'SRV01') { throw \"still named $env:COMPUTERNAME: the rename hasn't taken effect\" }\nAdd-Content -Path \"$env:windir\\System32\\drivers\\etc\\hosts\" -Value @('192.168.56.10 dc01', '192.168.56.12 srv02', '192.168.56.13 ws01')\nNew-NetFirewallRule -DisplayName 'isoloom 445' -Direction Inbound -Protocol TCP -LocalPort 445 -Action Allow | Out-Null\nNew-Item -ItemType Directory -Force C:\\ProgramData\\isoloom | Out-Null; Set-Content C:\\ProgramData\\isoloom\\ready 'ready'\n& powershell -NoProfile -ExecutionPolicy Bypass -File 'C:\\isoloom\\vagrant\\ConfigureRemotingForAnsible.ps1'; if ($LASTEXITCODE) { exit $LASTEXITCODE }\n"
    destination = "C:/isoloom/setup.ps1"
  }
  provisioner "remote-exec" {
    inline = ["powershell -NoProfile -ExecutionPolicy Bypass -File C:/isoloom/setup.ps1"]
  }
}

# Machine `srv02` (Windows): what may reach it.
resource "azurerm_network_security_group" "srv02" {
  name                = "${local.name}-srv02"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  security_rule {
    name                       = "net-lab"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "192.168.56.0/24"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "winrm"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "5985"
    source_address_prefix      = var.allowed_cidr
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "outbound"
    priority                   = 100
    direction                  = "Outbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_public_ip" "srv02" {
  name                = "${local.name}-srv02"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}

resource "azurerm_network_interface" "srv02_lab" {
  name                = "${local.name}-srv02-lab"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.lab.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "192.168.56.12"
    public_ip_address_id          = azurerm_public_ip.srv02.id
  }
}

resource "azurerm_network_interface_security_group_association" "srv02_lab" {
  network_interface_id      = azurerm_network_interface.srv02_lab.id
  network_security_group_id = azurerm_network_security_group.srv02.id
}

resource "azurerm_windows_virtual_machine" "srv02" {
  name                  = "${local.name}-srv02"
  computer_name         = "srv02"
  resource_group_name   = azurerm_resource_group.env.name
  location              = var.region
  size                  = "Standard_B2s"
  admin_username        = "isoloom"
  admin_password        = random_password.windows.result
  network_interface_ids = [azurerm_network_interface.srv02_lab.id]
  winrm_listener {
    protocol = "Http"
  }
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
    disk_size_gb         = 127
  }
  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-datacenter-gensecond"
    version   = "latest"
  }
  tags = local.tags
}

resource "terraform_data" "srv02" {
  triggers_replace = [azurerm_windows_virtual_machine.srv02.id]
  connection {
    type     = "winrm"
    host     = azurerm_public_ip.srv02.ip_address
    user     = "isoloom"
    password = random_password.windows.result
    https    = false
    use_ntlm = true
    timeout  = "30m"
  }
  provisioner "remote-exec" {
    inline = [var.auto_stop_minutes > 0 ? "powershell -NoProfile -Command \"Register-ScheduledTask -TaskName isoloom-auto-stop -Action (New-ScheduledTaskAction -Execute shutdown.exe -Argument '/s /t 0') -Trigger (New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(${var.auto_stop_minutes})) -User SYSTEM -RunLevel Highest -Force\"" : "cmd /c ver"]
  }
  provisioner "file" {
    source      = "${local.root}/vagrant/ConfigureRemotingForAnsible.ps1"
    destination = "C:/isoloom/vagrant/ConfigureRemotingForAnsible.ps1"
  }
  provisioner "file" {
    content     = "$ErrorActionPreference = 'Stop'\nif ($env:COMPUTERNAME -ne 'SRV02') { throw \"still named $env:COMPUTERNAME: the rename hasn't taken effect\" }\nAdd-Content -Path \"$env:windir\\System32\\drivers\\etc\\hosts\" -Value @('192.168.56.10 dc01', '192.168.56.11 srv01', '192.168.56.13 ws01')\nNew-NetFirewallRule -DisplayName 'isoloom 445' -Direction Inbound -Protocol TCP -LocalPort 445 -Action Allow | Out-Null\nNew-Item -ItemType Directory -Force C:\\ProgramData\\isoloom | Out-Null; Set-Content C:\\ProgramData\\isoloom\\ready 'ready'\n& powershell -NoProfile -ExecutionPolicy Bypass -File 'C:\\isoloom\\vagrant\\ConfigureRemotingForAnsible.ps1'; if ($LASTEXITCODE) { exit $LASTEXITCODE }\n"
    destination = "C:/isoloom/setup.ps1"
  }
  provisioner "remote-exec" {
    inline = ["powershell -NoProfile -ExecutionPolicy Bypass -File C:/isoloom/setup.ps1"]
  }
}

# Machine `ws01` (Windows): what may reach it.
resource "azurerm_network_security_group" "ws01" {
  name                = "${local.name}-ws01"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  security_rule {
    name                       = "net-lab"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "192.168.56.0/24"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "winrm"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "5985"
    source_address_prefix      = var.allowed_cidr
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "outbound"
    priority                   = 100
    direction                  = "Outbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_public_ip" "ws01" {
  name                = "${local.name}-ws01"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}

resource "azurerm_network_interface" "ws01_lab" {
  name                = "${local.name}-ws01-lab"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.lab.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "192.168.56.13"
    public_ip_address_id          = azurerm_public_ip.ws01.id
  }
}

resource "azurerm_network_interface_security_group_association" "ws01_lab" {
  network_interface_id      = azurerm_network_interface.ws01_lab.id
  network_security_group_id = azurerm_network_security_group.ws01.id
}

resource "azurerm_windows_virtual_machine" "ws01" {
  name                  = "${local.name}-ws01"
  computer_name         = "ws01"
  resource_group_name   = azurerm_resource_group.env.name
  location              = var.region
  size                  = "Standard_B2s"
  admin_username        = "isoloom"
  admin_password        = random_password.windows.result
  network_interface_ids = [azurerm_network_interface.ws01_lab.id]
  winrm_listener {
    protocol = "Http"
  }
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
    disk_size_gb         = 127
  }
  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-datacenter-gensecond"
    version   = "latest"
  }
  tags = local.tags
}

resource "terraform_data" "ws01" {
  triggers_replace = [azurerm_windows_virtual_machine.ws01.id]
  connection {
    type     = "winrm"
    host     = azurerm_public_ip.ws01.ip_address
    user     = "isoloom"
    password = random_password.windows.result
    https    = false
    use_ntlm = true
    timeout  = "30m"
  }
  provisioner "remote-exec" {
    inline = [var.auto_stop_minutes > 0 ? "powershell -NoProfile -Command \"Register-ScheduledTask -TaskName isoloom-auto-stop -Action (New-ScheduledTaskAction -Execute shutdown.exe -Argument '/s /t 0') -Trigger (New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(${var.auto_stop_minutes})) -User SYSTEM -RunLevel Highest -Force\"" : "cmd /c ver"]
  }
  provisioner "file" {
    source      = "${local.root}/vagrant/ConfigureRemotingForAnsible.ps1"
    destination = "C:/isoloom/vagrant/ConfigureRemotingForAnsible.ps1"
  }
  provisioner "file" {
    content     = "$ErrorActionPreference = 'Stop'\nif ($env:COMPUTERNAME -ne 'WS01') { throw \"still named $env:COMPUTERNAME: the rename hasn't taken effect\" }\nAdd-Content -Path \"$env:windir\\System32\\drivers\\etc\\hosts\" -Value @('192.168.56.10 dc01', '192.168.56.11 srv01', '192.168.56.12 srv02')\nNew-NetFirewallRule -DisplayName 'isoloom 445' -Direction Inbound -Protocol TCP -LocalPort 445 -Action Allow | Out-Null\nNew-Item -ItemType Directory -Force C:\\ProgramData\\isoloom | Out-Null; Set-Content C:\\ProgramData\\isoloom\\ready 'ready'\n& powershell -NoProfile -ExecutionPolicy Bypass -File 'C:\\isoloom\\vagrant\\ConfigureRemotingForAnsible.ps1'; if ($LASTEXITCODE) { exit $LASTEXITCODE }\n"
    destination = "C:/isoloom/setup.ps1"
  }
  provisioner "remote-exec" {
    inline = ["powershell -NoProfile -ExecutionPolicy Bypass -File C:/isoloom/setup.ps1"]
  }
}

# The controller (Ansible): every network may reach it, and SSH from allowed_cidr.
resource "azurerm_network_security_group" "isoloom_controller" {
  name                = "${local.name}-controller"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  security_rule {
    name                       = "net-lab"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "192.168.56.0/24"
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "ssh"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = var.allowed_cidr
    destination_address_prefix = "*"
  }
  security_rule {
    name                       = "outbound"
    priority                   = 100
    direction                  = "Outbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_public_ip" "isoloom_controller" {
  name                = "${local.name}-controller"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}

resource "azurerm_network_interface" "isoloom_controller_lab" {
  name                = "${local.name}-controller-lab"
  resource_group_name = azurerm_resource_group.env.name
  location            = var.region
  tags                = local.tags
  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.lab.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "192.168.56.253"
    public_ip_address_id          = azurerm_public_ip.isoloom_controller.id
  }
}

resource "azurerm_network_interface_security_group_association" "isoloom_controller_lab" {
  network_interface_id      = azurerm_network_interface.isoloom_controller_lab.id
  network_security_group_id = azurerm_network_security_group.isoloom_controller.id
}

resource "azurerm_linux_virtual_machine" "isoloom_controller" {
  name                  = "${local.name}-controller"
  resource_group_name   = azurerm_resource_group.env.name
  location              = var.region
  size                  = "Standard_B1ms"
  admin_username        = "isoloom"
  network_interface_ids = [azurerm_network_interface.isoloom_controller_lab.id]
  custom_data           = var.auto_stop_minutes > 0 ? base64encode("#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n") : null
  admin_ssh_key {
    username   = "isoloom"
    public_key = var.ssh_public_key
  }
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
    disk_size_gb         = 30
  }
  source_image_reference {
    publisher = "Debian"
    offer     = "debian-12"
    sku       = "12-gen2"
    version   = "latest"
  }
  tags = local.tags
}

resource "terraform_data" "isoloom_controller" {
  triggers_replace = [azurerm_linux_virtual_machine.isoloom_controller.id]
  connection {
    type        = "ssh"
    host        = azurerm_public_ip.isoloom_controller.ip_address
    user        = "isoloom"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown isoloom /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-controller.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-controller.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "file" {
    content     = tls_private_key.controller.private_key_openssh
    destination = "/tmp/isoloom-controller-key"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '192.168.56.10 dc01' '192.168.56.11 srv01' '192.168.56.12 srv02' '192.168.56.13 ws01' | sudo tee -a /etc/hosts >/dev/null",
      "sudo mkdir -p /etc/isoloom && sudo install -m 0600 /tmp/isoloom-controller-key /etc/isoloom/id_ed25519 && rm -f /tmp/isoloom-controller-key",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3-venv curl netcat-openbsd >/dev/null",
      "[ -x /opt/ansible/bin/ansible-playbook ] || { sudo python3 -m venv /opt/ansible && sudo /opt/ansible/bin/pip install -q 'ansible-core>=2.15,<2.17' pywinrm; }",
      "printf '%s' '[linux]\n\n[windows]\ndc01 ansible_host=192.168.56.10\nsrv01 ansible_host=192.168.56.11\nsrv02 ansible_host=192.168.56.12\nws01 ansible_host=192.168.56.13\n\n[linux:vars]\nansible_ssh_private_key_file=/etc/isoloom/id_ed25519\nansible_become=true\n\n[windows:vars]\nansible_user=isoloom\nansible_password=${random_password.windows.result}\nansible_connection=winrm\nansible_port=5985\nansible_winrm_scheme=http\nansible_winrm_transport=basic\nansible_winrm_server_cert_validation=ignore\nansible_winrm_operation_timeout_sec=400\nansible_winrm_read_timeout_sec=500\n\n[domain]\ndc01\nsrv01\nsrv02\nws01\n\n[dc]\ndc01\n\n[server]\nsrv01\nsrv02\n\n[workstation]\nws01\n\n[parent_dc]\ndc01\n\n[mssql]\nsrv02\n\n[mssql_ssms]\nsrv02\n\n[mssql_reporting]\nsrv02\n\n[elk_log]\ndc01\nsrv01\nws01\n\n[update]\ndc01\nsrv01\nws01\n\n[defender_on]\ndc01\nsrv01\nsrv02\nws01\n\n[sccm]\nsrv01\n' | sudo tee /etc/isoloom/inventory.ini >/dev/null",
      "sudo sh -c 'set -e\nmkdir -p /tmp/isoloom-facts\nexport PATH=/opt/ansible/bin:$PATH ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_GATHERING=smart ANSIBLE_FORKS=20 ANSIBLE_PIPELINING=True ANSIBLE_CACHE_PLUGIN=jsonfile ANSIBLE_CACHE_PLUGIN_CONNECTION=/tmp/isoloom-facts ANSIBLE_CACHE_PLUGIN_TIMEOUT=7200\ncd /opt/isoloom/ansible\nansible-galaxy install -r /opt/isoloom/ansible/requirements_311.yml\nansible-playbook -i /etc/isoloom/inventory.ini -i /opt/isoloom/ad/SCCM/data/inventory -e '\\''{\"sql_instance_name\":\"MSSQLSERVER\",\"sql_version\":\"MSSQL_2022\",\"admin_user\":\"administrator\",\"domain_name\":\"SCCM\",\"force_dns_server\":\"no\",\"dns_server\":\"x.x.x.x\",\"two_adapters\":\"yes\",\"dns_server_forwarder\":\"1.1.1.1\",\"enable_http_proxy\":\"no\",\"ad_http_proxy\":\"http://{{proxy_ip}}:{{proxy_port}}\",\"ad_https_proxy\":\"http://{{proxy_ip}}:{{proxy_port}}\",\"add_route\":\"no\",\"route_gateway\":\"192.168.56.1\",\"route_network\":\"10.0.0.0/8\",\"proxy_ip\":\"x.x.x.x\",\"proxy_port\":\"8080\"}'\\'' sccm.yml\n'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [terraform_data.dc01, terraform_data.srv01, terraform_data.srv02, terraform_data.ws01]
}

output "machines" {
  value = {
    dc01  = azurerm_public_ip.dc01.ip_address
    srv01 = azurerm_public_ip.srv01.ip_address
    srv02 = azurerm_public_ip.srv02.ip_address
    ws01  = azurerm_public_ip.ws01.ip_address
  }
}

output "ssh_users" {
  value = {
    dc01  = "isoloom"
    srv01 = "isoloom"
    srv02 = "isoloom"
    ws01  = "isoloom"
  }
}

output "ip" {
  value = azurerm_public_ip.isoloom_controller.ip_address
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}
